language: python
python:
  - "3.3"
# This was taken from https://github.com/mwaskom/seaborn/blob/master/.travis.yml
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/anaconda/bin:$PATH
install:
    - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
    - conda update conda --yes
    - source activate testenv
    - conda install --yes numpy scipy coveralls matplotlib
    - python setup.py install
script:  
    - python setup.py nosetests --with-coverage --cover-package=pyrvt --verbosity=2
after_success:
    - coveralls
