sudo: false
language: python
python:
  - "2.7"
  - "3.4"

# This was taken from https://github.com/mwaskom/seaborn/blob/master/.travis.yml
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH

install:
    - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
    - source activate testenv
    - conda install --yes numpy scipy matplotlib
    - pip install -r requirements.txt
    - python setup.py install

script:  
    - python setup.py nosetests --with-coverage --cover-package=pyrvt --verbosity=2

after_success:
    - coveralls

