language: python
python:
  - "3.3"
# Use binary installs for numpy and scipy
before_install:
    - sudo apt-get install python3-scipy python3-numpy
install:
    - python setup.py install
script:  
    - nosetests
